apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-1
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: test
spec:
  project: default
  destination:
    name: in-cluster
    namespace: default
  source:
    path: dev
    repoURL: https://github.com/cypress-test-u/promotion-flow-apps-examples.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
